### ISSUE TITLE
Keep empty lines in some cases

### ISSUE THREAD

**Issue by denizdogan** [marko-js/marko-prettyprint#18]
Thanks for making this tool!

It would be great if you could configure this with something like `maxEmptyLines` to have it preserve empty lines in some cases. In its current state, everything becomes so overly compact removing every empty line in the template.

**Comment by mlrawlings** [comment]
I agree.  I think empty lines need to be preserved, but multiple empty lines should be collapsed to a single empty line.  Not sure there's a need for a `maxEmptyLines` option.

**Comment by denizdogan** [comment]
No longer relevant to me, closing
