### ISSUE TITLE
support max-line-length

### ISSUE THREAD

**Issue by yomed** [marko-js/marko-prettyprint#4]
Follow up from https://github.com/marko-js/marko-migrate/issues/10

It would be useful to have the max-line-length style setting exposed for easier marko migrations from v2 to v3.

**Comment by patrick-steele-idem** [comment]
If you are interested in working on this, the current value for "max-line-length" is currently hard coded: https://github.com/marko-js/marko-prettyprint/blob/cd248406373bbf50c5298b81b96803f815e5e699/src/printHtmlElement.js#L12
